source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'schema_plus'
gem 'schema_associations'
gem 'devise'
gem 'dry_crud'
gem 'faye-rails'
gem 'thin'
gem 'therubyracer'
gem 'browserid-auth-rails'
gem 'simplecov'
